name: FFmpeg Build - Linux64 Nonfree 7.1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          ./makeimage.sh linux64 nonfree 7.1

      - name: Build FFmpeg
        run: |
          ./build.sh linux64 nonfree 7.1
          ls artifacts/ # Kiểm tra file

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-n7.1-latest-linux64-nonfree-7.1
          path: artifacts/ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz

      - name: Debug on Failure
        if: failure()
        run: |
          ls -la artifacts/
