name: FFmpeg Build - Linux64 Nonfree 7.1

on:
  push:
    branches: [ main ]          # Chạy khi push vào main
  workflow_dispatch:            # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest      # Chạy trên runner Ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Lấy mã nguồn

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2 # Cài Docker để build

      - name: Build Docker Image
        run: |
          ./makeimage.sh linux64 nonfree 7.1 # Tạo image với phụ thuộc nonfree-7.1

      - name: Build FFmpeg
        run: |
          ./build.sh linux64 nonfree 7.1     # Build bản linux64-nonfree-7.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3    # Đẩy kết quả lên artifacts
        with:
          name: ffmpeg-n7.1-latest-linux64-nonfree-7.1
          path: artifacts/ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
